// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit.
export const IMAGES = {
  "terrace-dusk": {
    "aspect": 1.5025678650036685,
    "widths": [
      640,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "terrace-crowd": {
    "aspect": 1.5025678650036685,
    "widths": [
      640,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "terrace-night": {
    "aspect": 1.5025678650036685,
    "widths": [
      640,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "victoria-stamp": {
    "aspect": 0.66552734375,
    "widths": [
      640,
      1280
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "terrace-screen": {
    "aspect": 1.0010090817356205,
    "widths": [
      640
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "fans": {
    "aspect": 1.5009746588693957,
    "widths": [
      640
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "night-party": {
    "aspect": 1,
    "widths": [
      640,
      1280
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "dancefloor": {
    "aspect": 1,
    "widths": [
      266
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "match-night": {
    "aspect": 1,
    "widths": [
      640,
      1280
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "world-cup-night": {
    "aspect": 0.6666666666666666,
    "widths": [
      640,
      1280
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "motogp-night": {
    "aspect": 1,
    "widths": [
      552
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "rugby-night": {
    "aspect": 1,
    "widths": [
      640
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "f1-night": {
    "aspect": 0.7465753424657534,
    "widths": [
      640,
      1280
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "football-aerial": {
    "aspect": 0.7465753424657534,
    "widths": [
      640,
      1280
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "rugby-aerial": {
    "aspect": 0.7465753424657534,
    "widths": [
      640,
      1280
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "f1-aerial": {
    "aspect": 0.7465753424657534,
    "widths": [
      640,
      1280
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "motogp-aerial": {
    "aspect": 0.7465753424657534,
    "widths": [
      640,
      1280
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "football-detail": {
    "aspect": 0.7465753424657534,
    "widths": [
      640,
      1280
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "rugby-detail": {
    "aspect": 0.7465753424657534,
    "widths": [
      640,
      1280
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "f1-detail": {
    "aspect": 0.7465753424657534,
    "widths": [
      640,
      1280
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "motogp-detail": {
    "aspect": 0.7465753424657534,
    "widths": [
      640,
      1280
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "party": {
    "aspect": 0.6666666666666666,
    "widths": [
      640,
      1280
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "night-terrace": {
    "aspect": 1,
    "widths": [
      640
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "foam-party": {
    "aspect": 1,
    "widths": [
      465
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "logo": {
    "aspect": 3.3575129533678756,
    "widths": [
      640
    ],
    "formats": [
      "webp"
    ]
  },
  "logo-alt": {
    "aspect": 3.3526370217166495,
    "widths": [
      640
    ],
    "formats": [
      "webp"
    ]
  },
  "icon": {
    "aspect": 1,
    "widths": [
      256
    ],
    "formats": [
      "webp"
    ]
  },
  "anniversary-40": {
    "aspect": 1.134433962264151,
    "widths": [
      640
    ],
    "formats": [
      "webp"
    ]
  },
  "premier-league": {
    "aspect": 2.3703703703703702,
    "widths": [
      480
    ],
    "formats": [
      "webp"
    ]
  },
  "rugby-league": {
    "aspect": 1.7881355932203389,
    "widths": [
      422
    ],
    "formats": [
      "webp"
    ]
  },
  "world-cup-2026": {
    "aspect": 1.4255765199161425,
    "widths": [
      480
    ],
    "formats": [
      "webp"
    ]
  },
  "f1": {
    "aspect": 1.5,
    "widths": [
      480
    ],
    "formats": [
      "webp"
    ]
  },
  "motogp": {
    "aspect": 3.395872420262664,
    "widths": [
      480
    ],
    "formats": [
      "webp"
    ]
  },
  "gaa": {
    "aspect": 2.5594262295081966,
    "widths": [
      480
    ],
    "formats": [
      "webp"
    ]
  },
  "world-cup-2026-white": {
    "aspect": 1.4255765199161425,
    "widths": [
      480
    ],
    "formats": [
      "webp"
    ]
  }
} as const;
export type ImageName = keyof typeof IMAGES;
