/**
 * Optimize brand assets from client/public/images/raw/ into responsive variants.
 *
 * Photos  → AVIF + WebP at [640, 1280, 1920] widths (skip widths larger than source)
 * Marks   → single WebP (transparency kept) at a sane max width + original PNG kept
 *
 * Output: client/public/images/<name>-<width>.<ext>  (photos)
 *         client/public/images/<name>.webp|png       (marks)
 *
 * Run: node scripts/optimize-images.mjs
 */
import sharp from "sharp";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const RAW = path.resolve(__dirname, "../assets-src");
const OUT = path.resolve(__dirname, "../client/public/images");

const PHOTO_WIDTHS = [640, 1280, 1920];

/** raw filename → output base name */
const PHOTOS = {
  "39ZAPM-1.jpg": "terrace-dusk",
  "34ZAPM.jpg": "terrace-crowd",
  "03ZAPM.jpg": "terrace-night",
  "27ZAPM.jpg": "victoria-stamp",
  "lloret-sports-bar-terrace.jpg": "terrace-screen",
  "SOR07244.webp": "fans",
  "e6d076b0-4216-11ef-84b7-39eb66fe642b.jpg.webp": "crowd-cheer",
};

const MARKS = {
  "QUEENVIC_color.png": { name: "logo", width: 640 },
  "QUEENVIC_color2.png": { name: "logo-alt", width: 640 },
  "cropped-QUEENVIC_icono-01.png": { name: "icon", width: 256 },
  "40th-aniversary-logo-Queen-Vic.png": { name: "anniversary-40", width: 640 },
  "Premier_League.png": { name: "premier-league", width: 480 },
  "rugby-football-league-logo-white.png": { name: "rugby-league", width: 480 },
  "football-world-cup-2026-e1774444864283.png": { name: "world-cup-2026", width: 480 },
  "f1-logo-formula-1-2026-2.png": { name: "f1", width: 480 },
  "motogp-logo-white-scaled-e1774444983994.png": { name: "motogp", width: 480 },
  "gaa-logo.png": { name: "gaa", width: 480 },
};

const manifest = {};

for (const [file, name] of Object.entries(PHOTOS)) {
  const src = path.join(RAW, file);
  if (!fs.existsSync(src)) {
    console.warn(`skip (missing): ${file}`);
    continue;
  }
  const meta = await sharp(src).metadata();
  const widths = PHOTO_WIDTHS.filter((w) => w <= meta.width);
  if (widths.length === 0) widths.push(meta.width);
  manifest[name] = { aspect: meta.width / meta.height, widths, formats: ["avif", "webp"] };

  for (const w of widths) {
    const base = sharp(src).resize(w).rotate();
    await base.clone().avif({ quality: 55 }).toFile(path.join(OUT, `${name}-${w}.avif`));
    await base.clone().webp({ quality: 72 }).toFile(path.join(OUT, `${name}-${w}.webp`));
  }
  console.log(`photo ${name}: ${widths.join(", ")}px (avif+webp)`);
}

for (const [file, { name, width }] of Object.entries(MARKS)) {
  const src = path.join(RAW, file);
  if (!fs.existsSync(src)) {
    console.warn(`skip (missing): ${file}`);
    continue;
  }
  const meta = await sharp(src).metadata();
  const w = Math.min(width, meta.width);
  await sharp(src).resize(w).webp({ quality: 88, alphaQuality: 95 }).toFile(path.join(OUT, `${name}.webp`));
  manifest[name] = { aspect: meta.width / meta.height, widths: [w], formats: ["webp"] };
  console.log(`mark ${name}: ${w}px (webp)`);
}

fs.writeFileSync(
  path.join(OUT, "manifest.json"),
  JSON.stringify(manifest, null, 2) + "\n",
);

// Typed manifest for the client (consumed by <Picture/>).
const ts = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit.
export const IMAGES = ${JSON.stringify(manifest, null, 2)} as const;
export type ImageName = keyof typeof IMAGES;
`;
fs.writeFileSync(path.resolve(__dirname, "../client/src/lib/image-manifest.ts"), ts);
console.log("\n✅ wrote manifest.json + image-manifest.ts");
